<?php

namespace AppBundle\Repository;

/**
 * ModeratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeratorRepository extends \Doctrine\ORM\EntityRepository
{
}
